[theme]
base = "light"
primaryColor = "#d0001d"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f7"
textColor = "#1a1a1a"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
